### ISSUE TITLE
The app's HTML results in a full-height Sidenav that  covers the toolbar instead of staying below it

### ISSUE THREAD

**Issue by mtevrst** [angular/material-start#137] opened 2016-07-05 09:10 UTC
Repo's clone gives this layout instead of the one shown in the readme:

![image](https://cloud.githubusercontent.com/assets/9102996/16579610/2bfd78a2-42be-11e6-98c4-caf0d682ca39.png)

Has the behavior of the Sidenav component been changed since this tutorial app was created? What is the way to get the layout shown in the readme?

**Comment by mtevrst** [comment] 2016-07-06 15:25
Is no one addressing the issues in this starter app?

**Comment by Axel186** [comment] 2016-08-11 07:59
I think the issue comes from [angular-material](https://material.angularjs.org/latest/) original source...

Check the screenshot of original website:
![screen shot 2016-08-11 at 10 48 54 am](https://cloud.githubusercontent.com/assets/11068030/17581895/425b1ed2-5fb1-11e6-9838-2e06c98f3872.png)

But, anyway - you can find other solution. I like how it looks when you adding md-toolbar to slide-nav:
![screen shot 2016-08-11 at 10 58 14 am](https://cloud.githubusercontent.com/assets/11068030/17582125/8f3e529a-5fb2-11e6-8fef-545335185a23.png)

Take a look at my example: http://codepen.io/anon/pen/ZOVvWX

**Comment by ThomasBurleson** [comment] 2016-08-11 15:57
@mtevrst - the `material-start` sidenav should not overlay the content. So good catch!
@Axel186 - the `material.angularjs.org` sidenav **SHOULD** overlay the content... that was also by design (as you indicated).

**Comment by Axel186** [comment] 2016-08-11 16:02
hmm... Just checked in Material Guide:

![screen shot 2016-08-11 at 7 00 53 pm](https://cloud.githubusercontent.com/assets/11068030/17595534/1c0dc122-5ff6-11e6-9ca5-e36960b91ee2.png)

[Material design Guide](https://material.google.com/)

**Comment by ThomasBurleson** [comment] 2016-08-11 16:17
@topherfangio - seems like a worthwhile fix.

**Comment by EladBezalel** [comment] 2016-08-11 16:57
Agree with @topherfangio,
if we wanted the sidenav to be toggled on desktop it should be beneath the toolbar for sure, but on mobile it should overlay the toolbar.

**Comment by ThomasBurleson** [comment] 2016-08-11 21:21
will not fix.

**Closed by ThomasBurleson** 2016-08-11 21:21 UTC
